services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    container_name: db
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
    ports:
      - $DB_PORT:3306
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"
      - ./data/mysql:/var/lib/mysql
    networks:
      - node-app
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    build:
      context: ./app
    restart: unless-stopped
    container_name: app
    env_file: .env
    ports:
      - $PORT:$PORT
    stdin_open: true
    tty: true
    networks:
      - node-app
    volumes:
      - ./app/:/usr/src/app

  nginx:
    restart: always
    depends_on:
    - app
    container_name: proxy
    build:
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - node-app


networks:
  node-app: